name: Publish on Modrinth    
 
on: [ pull_request, workflow_dispatch ]           

env:                                                                      
  JAVA_VERSION: 17      
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}          

permissions:
  contents: write

jobs:                                             
  build:                                          
    runs-on: ubuntu-latest                        
    steps:                                        
      - name: Check Environment Variables
        run: env

      - uses: madhead/read-java-properties@latest
        id: read_properties
        with:
          file: gradle.properties
          all: true

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

        env:
          mod_name: ${{ steps.read_properties.outputs.archives_base_name }}
          mod_version: ${{ steps.read_properties.outputs.mod_version }}
        
      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3                                   
        with:
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
          name: "${{ env.mod_name }} ${{ env.mod_version }}"
          modrinth-id: 5PsMUIsq                                             
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
        
          version-type: release
          changelog-file: CHANGELOG.md                                      
          loaders: fabric
          java: "${{env.JAVA_VERSION}}"
