name: Publish on Modrinth

on:
  push:
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:

env:
  JAVA_VERSION: 21
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: madhead/read-java-properties@latest
        id: read_properties
        with:
          file: gradle.properties
          all: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish Fabric Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
          name: "VinURL Fabric ${{ steps.read_properties.outputs.mod_version }}"
          modrinth-id: 5PsMUIsq
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          dependencies: |
            fabric-api
            owo-lib

          version-type: release
          changelog-file: CHANGELOG.md
          loaders: fabric
          java: "${{env.JAVA_VERSION}}"

      - name: Add Null Byte to Neoforge (Modrinth has Hashing Issues)
        run: |
          JAR_NAME="build/libs/vinurl-${{ steps.read_properties.outputs.mod_version }}.jar"
          echo -n -e "\x00" >> "$JAR_NAME"

      - name: Publish Neoforge Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
          name: "VinURL Neoforge ${{ steps.read_properties.outputs.mod_version }}"
          modrinth-id: 5PsMUIsq
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          dependencies: |
            forgified-fabric-api
            owo-lib
            connector

          version-type: release
          changelog-file: CHANGELOG.md
          loaders: neoforge
          java: "${{env.JAVA_VERSION}}"
