name: Publish on Modrinth

on:
  push:
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:

env:
  JAVA_VERSION: 21
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: madhead/read-java-properties@latest
        id: minecraft_version
        with:
          file: gradle.properties
          property: mod_minecraft_version_end

      - name: Extract version from CHANGELOG.md
        id: extract_version
        run: |
         
          VERSION=$(grep -oP '(?<=Version: )\d+\.\d+\.\d+' CHANGELOG.md | head -n 1)
          
          echo "mod_version=$VERSION" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish Fabric Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
          name: "VinURL ${{ env.mod_version }} for Fabric ${{ steps.minecraft_version.outputs.value }}"
          version: "${{ env.mod_version }}+${{ steps.minecraft_version.outputs.value }}-fabric"
          modrinth-id: 5PsMUIsq
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          dependencies: |
            fabric-api
            owo-lib

          version-type: release
          changelog-file: CHANGELOG.md
          loaders: fabric
          java: "${{env.JAVA_VERSION}}"

      - name: Build
        run: ./gradlew clean build -Pneoforge=true

      - name: Publish Neoforge Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
          name: "VinURL ${{ env.mod_version }} for Neoforge ${{ steps.minecraft_version.outputs.value }}"
          version: "${{ env.mod_version }}+${{ steps.minecraft_version.outputs.value }}-neoforge"
          modrinth-id: 5PsMUIsq
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          dependencies: |
            forgified-fabric-api
            owo-lib
            connector

          version-type: release
          changelog-file: CHANGELOG.md
          loaders: neoforge
          java: "${{env.JAVA_VERSION}}"
